# Project Name
TARGET = PhaseShapers

# Sources
CPP_SOURCES = main.cpp \
	phaseshapers.cpp \

DEBUG = 1

# Library Locations
LIBDAISY_DIR = ../externals/libDaisy/
DAISYSP_DIR = ../externals/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
